services:
  web-app:

    build: 
      context: .
    
    ports:
      - "8000:8000"
      # порт контейнера соответствует порту компа

    volumes:
      - ./service:/service
      # Подключаем папку service к локальному чето там
      # Чтобы при подключении питона не ребилдить каждый раз
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:

    image: postgres:14.6-alpine

    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

